/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PraktikumGUI_Login;

import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daffa Danendra
 */
public class UserManagementFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserManagementFrame.class.getName());

    /**
     * Creates new form UserManagementFrame
     */
   public UserManagementFrame() {
    initComponents();
    
    // QUICK FIX: Hardcode session untuk testing
    if ((Session.username == null || Session.username.isEmpty()) && jTable1.getRowCount() > 0) {
        System.out.println("=== APPLYING QUICK FIX ===");
        Session.username = "";
        Session.role = "admin";
        System.out.println("Hardcoded - Username: " + Session.username + ", Role: " + Session.role);
    }
    
    setTitle("User Management - Login sebagai: " + Session.username + " (" + Session.role + ")");
    loadUserData();
    updateButtonStates();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Username", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
System.out.println("=== FORCE ENABLE EDIT ===");
    
    int row = jTable1.getSelectedRow();
    System.out.println("Selected row: " + row);
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "PILIH USER DULU! Klik baris di tabel.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int id = (int) model.getValueAt(row, 0);
    String username = (String) model.getValueAt(row, 1);
    String role = (String) model.getValueAt(row, 2);
    
    System.out.println("Editing - ID: " + id + ", User: " + username + ", Role: " + role);
    
    // Simple edit dialog
    String newUsername = JOptionPane.showInputDialog(this, 
        "Edit username untuk " + username + ":", username);
    
    if (newUsername != null && !newUsername.trim().isEmpty()) {
        updateUser(id, newUsername.trim(), role);
    }               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         System.out.println("Delete button clicked - Admin check: " + isAdmin());
        
        if (!isAdmin()) {
            JOptionPane.showMessageDialog(this, 
                "Hanya admin yang dapat menghapus user!", 
                "Akses Ditolak", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih user yang akan dihapus!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int id = (int) model.getValueAt(row, 0);
        String username = (String) model.getValueAt(row, 1);

        // Cegah penghapusan diri sendiri
        if (username.equals(Session.username)) {
            JOptionPane.showMessageDialog(this, 
                "Tidak dapat menghapus akun sendiri!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus user: " + username + "?", "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            deleteUser(id);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new WelcomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagementFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 private void loadUserData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear tabel

        try (Connection conn = koneksi.getConnection()) {
            String sql = "SELECT id, username, role FROM users ORDER BY id";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            int rowCount = 0;
            while (rs.next()) {
                int id = rs.getInt("id");
                String username = rs.getString("username");
                String role = rs.getString("role");
                
                model.addRow(new Object[]{ id, username, role });
                rowCount++;
            }

            System.out.println("Data loaded: " + rowCount + " users");
            
            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Tidak ada data user di database!\nPastikan tabel 'users' sudah ada dan berisi data.", 
                    "Data Kosong", 
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error koneksi database: " + e.getMessage() + 
                "\nPastikan:\n1. Database PostgreSQL berjalan\n2. Tabel 'users' ada\n3. Koneksi database benar", 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private boolean isUsernameExists(String username) {
        try (Connection conn = koneksi.getConnection()) {
            String sql = "SELECT COUNT(*) FROM users WHERE username = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private void updateUser(int id, String newUsername, String newRole) {
        try (Connection conn = koneksi.getConnection()) {
            PreparedStatement stmt = conn.prepareStatement(
                "UPDATE users SET username = ?, role = ? WHERE id = ?");
            stmt.setString(1, newUsername);
            stmt.setString(2, newRole);
            stmt.setInt(3, id);
            
            int rowsAffected = stmt.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "User berhasil diupdate!");
                loadUserData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate user!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    private void deleteUser(int id) {
        try (Connection conn = koneksi.getConnection()) {
            PreparedStatement stmt = conn.prepareStatement(
                "DELETE FROM users WHERE id = ?");
            stmt.setInt(1, id);
            
            int rowsAffected = stmt.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "User berhasil dihapus!");
                loadUserData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus user!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

private void updateButtonStates() {
    boolean isAdmin = isAdmin();
    
    System.out.println("=== BUTTON STATES ===");
    System.out.println("Edit Button Enabled: " + isAdmin);
    System.out.println("Delete Button Enabled: " + isAdmin);
    System.out.println("====================");
    
    jButton1.setEnabled(isAdmin);
    jButton2.setEnabled(isAdmin);

    if (isAdmin) {
        jButton1.setBackground(new java.awt.Color(0, 123, 255)); // Biru
        jButton2.setBackground(new java.awt.Color(220, 53, 69)); // Merah
        jButton1.setForeground(Color.WHITE);
        jButton2.setForeground(Color.WHITE);
    } else {
        jButton1.setBackground(Color.LIGHT_GRAY);
        jButton2.setBackground(Color.LIGHT_GRAY);
    }
}

private boolean isAdmin() {
    if (Session.role == null) {
        System.out.println("ERROR: Session.role is NULL");
        return false;
    }
    
    boolean isAdmin = "admin".equalsIgnoreCase(Session.role.trim());
    System.out.println("Admin Check - Role: '" + Session.role + "', Is Admin: " + isAdmin);
    return isAdmin;
}

    static class koneksi {

        public static Connection getConnection() throws SQLException {
            String url = "jdbc:postgresql://localhost:5432/LoginJava";
            String user = "postgres";
            String pass = "Danendra07";
            return DriverManager.getConnection(url, user, pass);
        }
    }
}
